### ISSUE TITLE
Wrong ending checking function

### ISSUE THREAD

**Issue by Buranek** [LonamiWebs/Klooni1010#15]
![1](https://cloud.githubusercontent.com/assets/6697344/23097269/a7a14804-f640-11e6-9d59-611218f6d168.png)
![2](https://cloud.githubusercontent.com/assets/6697344/23097270/a90fdcc8-f640-11e6-887c-bc6c76af0b84.png)
See attached screenshots. Bug appears after placing one or two block of loosing session. Don't know, how to explain it better.

**Comment by XyLoNaMiyX** [comment]
On the first screenshot, open the menu with the back key. It should say "no moves left". You can go back to the game to take a screenshot to your score, for example (it's intentional), although the menu should have opened itself.

On the second one, you can put the `L` on the bottom left square empty zone.

> Don't know, how to explain it better.

Would be great if you tried again :P

**Comment by Buranek** [comment]
Ok, it seems like a cancelled the menu open. If it appears again, I'll give a proof.

**Comment by XyLoNaMiyX** [comment]
I'm going to close this to remove some noise from the issues section. Feel free to open it if you do manage to give a proof!

**Comment by Buranek** [comment]
Ok.
