### ISSUE TITLE
Pieces are not moving at same speed as touch

### ISSUE THREAD

**Issue by smarek** [LonamiWebs/Klooni1010#3]
Hi,
First of all, terrific work, this game rock man :) I kinda am addicted already.

Second, I've just installed update in FDroid, and it seems to me, that something related to touch/move detection changed.

Compared to v0.1 I struggle with
  - Getting pieces to move (touch/drag fails a lot, detection area could be full 1/3rd of space below game board)
  - When I move the piece up it flings beyond my finger (previously was right under it)

Wouldn't bother me in normal mode, but it's really much different and I fail the quick-time mode because of it ;)

Also I expected the stats/leaderboard to be fixed. Do you plan to provide that later or did you dismissed the feature completely?

Thank you!

**Comment by XyLoNaMiyX** [comment]
> First of all, terrific work, this game rock man :)

Thank you :)

> Getting pieces to move (touch/drag fails a lot, detection area could be full 1/3rd of space below game board)

Yeah I shrinked the size of the pieces because some people, including #2, complained about it. But I can make it that the whole 1/3 area is "pickable" and not only the pieces. This perhaps is a bit weird since then you'd be able to pick the pieces by tapping on empty space... But to be honest, it would just be handier.

> When I move the piece up it flings beyond my finger (previously was right under it)

Yes, this was actually an idea from my friend @AlbertWDev, ported from the original game. For example, 1x1 pieces are so small that you'd cover them with your finger. I pushed them up so you actually saw where the pieces were.

> Wouldn't bother me in normal mode, but it's really much different and I fail the quick-time mode because of it ;)

Maybe people just need some more time until they get used? Just like they got used to how it worked before. I don't know, I also think that the benefit from actually seeing the piece and not covering it can be helpful? Not sure. We can argue about that. The game is still in early stages and I like community feedback first.

> Also I expected the stats/leaderboard to be fixed. Do you plan to provide that later

I do plan to add it later, at least for offline mode. I think it would also be great if I could get some free host or something to just store the scores from all over the world (of course, with the **explicit consent** from the player. I won't do network stuff unless the player decides to). Maybe the play button could be 2/3 and the time mode on the right of it 1/3, so the stats button got back to its place. Uhm.

**Comment by XyLoNaMiyX** [comment]
Funny how I forgot the main point of the issue, "_Pieces are not moving at same speed as touch_". There is an interpolation between the current piece position and where it should go (wherever you're holding the finger). In my opinion, it looks nicer with this because it feels smoother. If the problem with this is that the time mode is harder, then consider it a challenge ;). If that's not the reason, you think that I should really remove the "smoothing"?

**Comment by StefanBrand** [comment]
I think it's good that in the latest version the 1x1 tile doesn't get covered. I was confused at first, but this is simply a trade-off with touch screens.

**Comment by XyLoNaMiyX** [comment]
> I think it's good that in the latest version the 1x1 tile doesn't get covered.

It should be kept then, right?

> but this is simply a trade-off with touch screens.

Yep, it won't happen on desktop because the mouse won't ever cover the piece.

**Comment by flasheater** [comment]
I would definitely keep the smoothing but adjust the  speed of the transition to something in between 50 and 150ms.
When it comes to animations in UI, try to make them faster than feels right during development. That is because as a developer you hyperfocus on the animation itself whereas the user just wants to get something done and long animations are essentially lag.

**Comment by XyLoNaMiyX** [comment]
> but adjust the speed of the transition to something in between 50 and 150ms.

The problem is there is no such thing as speed, it currently is an interpolation between the current position and the mouse position. To be more precise, on every frame, 40% of the path is "walked" (if it had to move from `x: 0` to `x: 100`, it would go `x: 40`, `x: 64`, `x: 73.6`…), although this can be used to calculate the speed more or less. However, 50/150ms relative to what?

Also, it does look faster if I change the interpolation to be 50%. It just doesn't feel right with 60%. I guess it could be done. For comparision, assuming we start at `0px`, end at `1000px` and an error of `1px` is enough on 30fps:
- With `0.4` it takes `14` frames or `~466ms`.
- With `0.5` it takes `10` frames or `~333ms`.
- With `0.6` it takes `8` frames or `~266ms` (but the jump is obviously more than half now, more noticeable).

Bear in mind that if we let the error be larger, say `10px`, the times are `333ms`, `233ms` and `200ms`. Hard to compare. So approximately `~x1.4` speed up. Not even sure people can move their finger so fast, but I guess there'll always be some pro-players.

**Comment by XyLoNaMiyX** [comment]
Let's get some issues closes see if we can pump the version up to `v0.4`, shouldn't we? I've been waiting for a bit but I'm impatient (sorry about that! I don't like to have uncommited changes sparsed).

As discussed before and shown by the [gifs](https://github.com/LonamiWebs/Klooni1010/issues/3#issuecomment-278934878), I won't be disabling the animation because it looks a bit odd, but it's _faster_, so don't worry too much about it!

> When I move the piece up it flings beyond my finger (previously was right under it)

About that, I consider it a feature. If it _really_ itches you please feel free to open another issue where we can discuss it in more detail and let more people participate. I personaly think it does more good than harm (maybe not inmediatly, but perhaps in a while, one only needs to get used to it).
