### ISSUE TITLE
UI is slightly too small in Nexus 6p

### ISSUE THREAD

**Issue by vanitasvitae** [LonamiWebs/Klooni1010#8]
Hi
The UI elements (menu and game oder screen) are a little too small on my device. I noticed that on the screenshots in this repo the UI is way bigger. It would be nice, if the size scales with screen resolution :)

Nice game though :)

**Comment by XyLoNaMiyX** [comment]
> The UI elements (menu and game oder screen) are a little too small on my device.

It probably has a high dpi. I don't like it either that in my phone the buttons seem smaller than how they look on the desktop. Not sure if there's a way to work around this with libGDX tables but I will take a look into it.

> Nice game though :)

Thanks, glad you like it! Feel free to contribute more ideas if any as well :)

**Comment by Lonami** [comment]
Partial fix, at least a larger texture is now chosen, though not resized to the exact size so it looked the same on all devices. I tried working with the [ortographic camera](https://github.com/libgdx/libgdx/wiki/Orthographic-camera) and using the [FillViewport](https://github.com/libgdx/libgdx/wiki/Viewports#fillviewport) to achieve this same look on all devices, but it's kind of complex.

I think this is a good solution because no resizing is required, the assets are already at their (closest) optimal sizes. Also, if I happen to use to viewport and camera, then larger sizes would need to be loaded on devices with low specifications. So probably a combination of both… But harder! :)

Let's update the font too, and close this issue - feel free to open it again if you feel that I'm missing something.

**Comment by Lonami** [comment]
There we are, commit [`13d837a`](https://github.com/LonamiWebs/Klooni1010/commit/13d837ad4b7bc3ed7c470e04730d7b9dc8868196) brings more font sizes. I hate that it requires so, *so* many lines of text files to specify the fonts but I'm not sure if F-Droid guys would accept [Gdx FreeType](https://github.com/libgdx/libgdx/wiki/Gdx-freetype)…

**Comment by vanitasvitae** [comment]
What does @krt16s say to the font thingy?

**Comment by Lonami** [comment]
> What does @krt16s say to the font thingy?

I have not asked him yet.
